/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: v2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ShipEngine : The engine determines how quickly a ship travels between waypoints.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShipEngine {
    /// The symbol of the engine.
    #[serde(rename = "symbol")]
    pub symbol: Symbol,
    /// The name of the engine.
    #[serde(rename = "name")]
    pub name: String,
    /// The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases.
    #[serde(rename = "condition")]
    pub condition: f64,
    /// The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time.
    #[serde(rename = "integrity")]
    pub integrity: f64,
    /// The description of the engine.
    #[serde(rename = "description")]
    pub description: String,
    /// The speed stat of this engine. The higher the speed, the faster a ship can travel from one point to another. Reduces the time of arrival when navigating the ship.
    #[serde(rename = "speed")]
    pub speed: i32,
    #[serde(rename = "requirements")]
    pub requirements: Box<models::ShipRequirements>,
    /// The overall quality of the component, which determines the quality of the component. High quality components return more ships parts and ship plating when a ship is scrapped. But also require more of these parts to repair. This is transparent to the player, as the parts are bought from/sold to the marketplace.
    #[serde(rename = "quality", skip_serializing_if = "Option::is_none")]
    pub quality: Option<f64>,
}

impl ShipEngine {
    /// The engine determines how quickly a ship travels between waypoints.
    pub fn new(
        symbol: Symbol,
        name: String,
        condition: f64,
        integrity: f64,
        description: String,
        speed: i32,
        requirements: models::ShipRequirements,
        quality: Option<f64>,
    ) -> ShipEngine {
        ShipEngine {
            symbol,
            name,
            condition,
            integrity,
            description,
            speed,
            requirements: Box::new(requirements),
            quality,
        }
    }
}
/// The symbol of the engine.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
    sqlx::Type,
    async_graphql::Enum,
)]
#[sqlx(type_name = "ship_engine_symbol")]
#[graphql(name = "ShipEngineSymbol")]
pub enum Symbol {
    #[serde(rename = "ENGINE_IMPULSE_DRIVE_I")]
    #[sqlx(rename = "ENGINE_IMPULSE_DRIVE_I")]
    ImpulseDriveI,
    #[serde(rename = "ENGINE_ION_DRIVE_I")]
    #[sqlx(rename = "ENGINE_ION_DRIVE_I")]
    IonDriveI,
    #[serde(rename = "ENGINE_ION_DRIVE_II")]
    #[sqlx(rename = "ENGINE_ION_DRIVE_II")]
    IonDriveIi,
    #[serde(rename = "ENGINE_HYPER_DRIVE_I")]
    #[sqlx(rename = "ENGINE_HYPER_DRIVE_I")]
    HyperDriveI,
}

impl From<Symbol> for models::TradeSymbol {
    fn from(val: Symbol) -> Self {
        match val {
            Symbol::ImpulseDriveI => models::TradeSymbol::EngineImpulseDriveI,
            Symbol::IonDriveI => models::TradeSymbol::EngineIonDriveI,
            Symbol::IonDriveIi => models::TradeSymbol::EngineIonDriveIi,
            Symbol::HyperDriveI => models::TradeSymbol::EngineHyperDriveI,
        }
    }
}

impl Default for Symbol {
    fn default() -> Symbol {
        Self::ImpulseDriveI
    }
}
