/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: v2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ShipMount : A mount is installed on the exterier of a ship.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShipMount {
    /// Symbol of this mount.
    #[serde(rename = "symbol")]
    pub symbol: Symbol,
    /// Name of this mount.
    #[serde(rename = "name")]
    pub name: String,
    /// Description of this mount.
    #[serde(rename = "description")]
    pub description: String,
    /// Mounts that have this value, such as mining lasers, denote how powerful this mount's capabilities are.
    #[serde(rename = "strength", skip_serializing_if = "Option::is_none")]
    pub strength: Option<i32>,
    /// Mounts that have this value denote what goods can be produced from using the mount.
    #[serde(rename = "deposits", skip_serializing_if = "Option::is_none")]
    pub deposits: Option<Vec<Deposits>>,
    #[serde(rename = "requirements")]
    pub requirements: Box<models::ShipRequirements>,
}

impl ShipMount {
    /// A mount is installed on the exterier of a ship.
    pub fn new(
        symbol: Symbol,
        name: String,
        description: String,
        requirements: models::ShipRequirements,
    ) -> ShipMount {
        ShipMount {
            symbol,
            name,
            description,
            strength: None,
            deposits: None,
            requirements: Box::new(requirements),
        }
    }
}
/// Symbol of this mount.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
    sqlx::Type,
    async_graphql::Enum,
)]
#[sqlx(type_name = "ship_mount_symbol")]
#[graphql(name = "ShipMountSymbol")]
pub enum Symbol {
    #[serde(rename = "MOUNT_GAS_SIPHON_I")]
    #[sqlx(rename = "MOUNT_GAS_SIPHON_I")]
    GasSiphonI,
    #[serde(rename = "MOUNT_GAS_SIPHON_II")]
    #[sqlx(rename = "MOUNT_GAS_SIPHON_II")]
    GasSiphonIi,
    #[serde(rename = "MOUNT_GAS_SIPHON_III")]
    #[sqlx(rename = "MOUNT_GAS_SIPHON_III")]
    GasSiphonIii,
    #[serde(rename = "MOUNT_SURVEYOR_I")]
    #[sqlx(rename = "MOUNT_SURVEYOR_I")]
    SurveyorI,
    #[serde(rename = "MOUNT_SURVEYOR_II")]
    #[sqlx(rename = "MOUNT_SURVEYOR_II")]
    SurveyorIi,
    #[serde(rename = "MOUNT_SURVEYOR_III")]
    #[sqlx(rename = "MOUNT_SURVEYOR_III")]
    SurveyorIii,
    #[serde(rename = "MOUNT_SENSOR_ARRAY_I")]
    #[sqlx(rename = "MOUNT_SENSOR_ARRAY_I")]
    SensorArrayI,
    #[serde(rename = "MOUNT_SENSOR_ARRAY_II")]
    #[sqlx(rename = "MOUNT_SENSOR_ARRAY_II")]
    SensorArrayIi,
    #[serde(rename = "MOUNT_SENSOR_ARRAY_III")]
    #[sqlx(rename = "MOUNT_SENSOR_ARRAY_III")]
    SensorArrayIii,
    #[serde(rename = "MOUNT_MINING_LASER_I")]
    #[sqlx(rename = "MOUNT_MINING_LASER_I")]
    MiningLaserI,
    #[serde(rename = "MOUNT_MINING_LASER_II")]
    #[sqlx(rename = "MOUNT_MINING_LASER_II")]
    MiningLaserIi,
    #[serde(rename = "MOUNT_MINING_LASER_III")]
    #[sqlx(rename = "MOUNT_MINING_LASER_III")]
    MiningLaserIii,
    #[serde(rename = "MOUNT_LASER_CANNON_I")]
    #[sqlx(rename = "MOUNT_LASER_CANNON_I")]
    LaserCannonI,
    #[serde(rename = "MOUNT_MISSILE_LAUNCHER_I")]
    #[sqlx(rename = "MOUNT_MISSILE_LAUNCHER_I")]
    MissileLauncherI,
    #[serde(rename = "MOUNT_TURRET_I")]
    #[sqlx(rename = "MOUNT_TURRET_I")]
    TurretI,
}

impl Default for Symbol {
    fn default() -> Symbol {
        Self::GasSiphonI
    }
}
/// Mounts that have this value denote what goods can be produced from using the mount.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Deposits {
    #[serde(rename = "QUARTZ_SAND")]
    QuartzSand,
    #[serde(rename = "SILICON_CRYSTALS")]
    SiliconCrystals,
    #[serde(rename = "PRECIOUS_STONES")]
    PreciousStones,
    #[serde(rename = "ICE_WATER")]
    IceWater,
    #[serde(rename = "AMMONIA_ICE")]
    AmmoniaIce,
    #[serde(rename = "IRON_ORE")]
    IronOre,
    #[serde(rename = "COPPER_ORE")]
    CopperOre,
    #[serde(rename = "SILVER_ORE")]
    SilverOre,
    #[serde(rename = "ALUMINUM_ORE")]
    AluminumOre,
    #[serde(rename = "GOLD_ORE")]
    GoldOre,
    #[serde(rename = "PLATINUM_ORE")]
    PlatinumOre,
    #[serde(rename = "DIAMONDS")]
    Diamonds,
    #[serde(rename = "URANITE_ORE")]
    UraniteOre,
    #[serde(rename = "MERITIUM_ORE")]
    MeritiumOre,
}

impl From<Symbol> for models::TradeSymbol {
    fn from(value: Symbol) -> Self {
        match value {
            Symbol::GasSiphonI => models::TradeSymbol::MountGasSiphonI,
            Symbol::GasSiphonIi => models::TradeSymbol::MountGasSiphonIi,
            Symbol::GasSiphonIii => models::TradeSymbol::MountGasSiphonIii,
            Symbol::SurveyorI => models::TradeSymbol::MountSurveyorI,
            Symbol::SurveyorIi => models::TradeSymbol::MountSurveyorIi,
            Symbol::SurveyorIii => models::TradeSymbol::MountSurveyorIii,
            Symbol::SensorArrayI => models::TradeSymbol::MountSensorArrayI,
            Symbol::SensorArrayIi => models::TradeSymbol::MountSensorArrayIi,
            Symbol::SensorArrayIii => models::TradeSymbol::MountSensorArrayIii,
            Symbol::MiningLaserI => models::TradeSymbol::MountMiningLaserI,
            Symbol::MiningLaserIi => models::TradeSymbol::MountMiningLaserIi,
            Symbol::MiningLaserIii => models::TradeSymbol::MountMiningLaserIii,
            Symbol::LaserCannonI => models::TradeSymbol::MountLaserCannonI,
            Symbol::MissileLauncherI => models::TradeSymbol::MountMissileLauncherI,
            Symbol::TurretI => models::TradeSymbol::MountTurretI,
        }
    }
}

impl Default for Deposits {
    fn default() -> Deposits {
        Self::QuartzSand
    }
}
