control_start_sleep = 0
control_active = true
scrapper_start_sleep = 1000
scrap_agents = false
update_all_systems = true
max_miners_per_waypoint = 12
# max_update_interval = 1800 #60 * 30
max_update_interval = 3600
antimatter_price = 6000
default_purchase_price = 100
default_sell_price = 150
ship_purchase_stop = false
ship_purchase_percentile = 25.0
expand = true
use_exploration_fleet = false
iron_reserve = 100000
