services:
  postgres:
    image: postgres:14-alpine
    container_name: spacetraders-postgres
    # restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  
  jaeger:
    image: jaegertracing/all-in-one:1.47
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
      - OTEL_BSP_MAX_QUEUE_SIZE=8192
      - OTEL_BSP_SCHEDULE_DELAY=100
    ports:
      - "6831:6831/udp"  # Jaeger compact Thrift protocol (UDP)
      - "6832:6832/udp"  # Jaeger binary Thrift protocol (UDP)
      - "5778:5778"      # Jaeger agent HTTP management port
      - "16686:16686"    # Jaeger query UI port
      - "4317:4317"      # Jaeger gRPC HTTP collector port
      - "4318:4318"      # Jaeger gRPC HTTP collector port (encrypted)
      - "14250:14250"    # Jaeger gRPC tracing port
      - "14268:14268"    # Jaeger gRPC HTTP internal service communication port
      - "14269:14269"    # Jaeger gRPC HTTP internal service communication port (encrypted)
      - "9411:9411"      # Zipkin collector port