-- Add up migration script here
CREATE TABLE public.ship_state (
  id bigserial NOT NULL,
  symbol character varying NOT NULL,
  display_name character varying NOT NULL,
  role ship_info_role NOT NULL,
  active boolean NOT NULL,
  engine_speed integer NOT NULL,
  engine_condition double precision NOT NULL,
  engine_integrity double precision NOT NULL,
  frame_condition double precision NOT NULL,
  frame_integrity double precision NOT NULL,
  reactor_condition double precision NOT NULL,
  reactor_integrity double precision NOT NULL,
  fuel_capacity integer NOT NULL,
  fuel_current integer NOT NULL,
  cargo_capacity integer NOT NULL,
  cargo_units integer NOT NULL,
  cargo_inventory jsonb NOT NULL,
  mounts ship_mount_symbol [] NOT NULL,
  modules ship_module_symbol [] NOT NULL,
  cooldown_expiration timestamp without time zone,
  flight_mode character varying NOT NULL,
  nav_status character varying NOT NULL,
  system_symbol character varying NOT NULL,
  waypoint_symbol character varying NOT NULL,
  route_arrival timestamp without time zone NOT NULL,
  route_departure timestamp without time zone NOT NULL,
  route_destination_symbol character varying NOT NULL,
  route_destination_system character varying NOT NULL,
  route_origin_symbol character varying NOT NULL,
  route_origin_system character varying NOT NULL,
  auto_pilot_arrival timestamp without time zone,
  auto_pilot_departure_time timestamp without time zone,
  auto_pilot_destination_symbol character varying,
  auto_pilot_destination_system_symbol character varying,
  auto_pilot_origin_symbol character varying,
  auto_pilot_origin_system_symbol character varying,
  auto_pilot_distance double precision,
  auto_pilot_fuel_cost integer,
  auto_pilot_travel_time double precision,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);