-- Add up migration script here
ALTER TYPE public.ship_frame_symbol
ADD VALUE 'FRAME_BULK_FREIGHTER'
AFTER 'FRAME_CARRIER';
ALTER TYPE public.ship_type
ADD VALUE 'SHIP_BULK_FREIGHTER'
AFTER 'SHIP_SURVEYOR';
ALTER TYPE public.trade_symbol
ADD VALUE 'FRAME_BULK_FREIGHTER'
AFTER 'SHIP_SURVEYOR';
ALTER TYPE public.trade_symbol
ADD VALUE 'SHIP_BULK_FREIGHTER'
AFTER 'FRAME_BULK_FREIGHTER';