-- Add up migration script here
CREATE TABLE public.ship_state (
  id bigserial NOT NULL,
  symbol character varying NOT NULL,
  display_name character varying NOT NULL,
  role ship_info_role NOT NULL,
  active boolean NOT NULL,
  engine_speed integer NOT NULL,
  engine_condition double precision NOT NULL,
  engine_integrity double precision NOT NULL,
  frame_condition double precision NOT NULL,
  frame_integrity double precision NOT NULL,
  reactor_condition double precision NOT NULL,
  reactor_integrity double precision NOT NULL,
  fuel_capacity integer NOT NULL,
  fuel_current integer NOT NULL,
  cargo_capacity integer NOT NULL,
  cargo_units integer NOT NULL,
  cargo_inventory jsonb NOT NULL,
  mounts ship_mount_symbol [] NOT NULL,
  modules ship_module_symbol [] NOT NULL,
  reactor_symbol ship_reactor_symbol NOT NULL,
  frame_symbol ship_frame_symbol NOT NULL,
  engine_symbol ship_engine_symbol NOT NULL,
  cooldown_expiration timestamp with time zone,
  cooldown integer,
  flight_mode character varying NOT NULL,
  nav_status character varying NOT NULL,
  system_symbol character varying NOT NULL,
  waypoint_symbol character varying NOT NULL,
  route_arrival timestamp with time zone NOT NULL,
  route_departure timestamp with time zone NOT NULL,
  route_destination_symbol character varying NOT NULL,
  route_destination_system character varying NOT NULL,
  route_origin_symbol character varying NOT NULL,
  route_origin_system character varying NOT NULL,
  auto_pilot_arrival timestamp with time zone,
  auto_pilot_departure_time timestamp with time zone,
  auto_pilot_destination_symbol character varying,
  auto_pilot_destination_system_symbol character varying,
  auto_pilot_origin_symbol character varying,
  auto_pilot_origin_system_symbol character varying,
  auto_pilot_distance double precision,
  auto_pilot_fuel_cost integer,
  auto_pilot_travel_time double precision,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  CONSTRAINT ship_symbol_relation FOREIGN KEY ("symbol") REFERENCES public.ship_info (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT waypoint_symbol_relation FOREIGN KEY ("waypoint_symbol") REFERENCES public.waypoint (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT route_origin_symbol_relation FOREIGN KEY ("route_origin_symbol") REFERENCES public.waypoint (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT route_destination_symbol_relation FOREIGN KEY ("route_destination_symbol") REFERENCES public.waypoint (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT auto_pilot_origin_symbol_relation FOREIGN KEY ("auto_pilot_origin_symbol") REFERENCES public.waypoint (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT auto_pilot_destination_symbol_relation FOREIGN KEY ("auto_pilot_destination_symbol") REFERENCES public.waypoint (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT system_symbol_relation FOREIGN KEY ("system_symbol") REFERENCES public.system (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT route_origin_system_relation FOREIGN KEY ("route_origin_system") REFERENCES public.system (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT route_destination_system_relation FOREIGN KEY ("route_destination_system") REFERENCES public.system (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT auto_pilot_origin_system_symbol_relation FOREIGN KEY ("auto_pilot_origin_system_symbol") REFERENCES public.system (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT auto_pilot_destination_system_symbol_relation FOREIGN KEY ("auto_pilot_destination_system_symbol") REFERENCES public.system (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT reactor_symbol_relation FOREIGN KEY ("reactor_symbol") REFERENCES public.reactor_info (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT frame_symbol_relation FOREIGN KEY ("frame_symbol") REFERENCES public.frame_info (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  -- CONSTRAINT mounts_relation FOREIGN KEY (mounts) REFERENCES public.mount_info (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  -- CONSTRAINT modules_relation FOREIGN KEY (modules) REFERENCES public.module_info (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
  CONSTRAINT engine_symbol_relation FOREIGN KEY ("engine_symbol") REFERENCES public.engine_info (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);