pub mod assignment_management;
mod fleet_manager;
pub mod fleet_population;
pub mod message;
mod messanger;
mod ship_capabilities;
mod ship_procurement_manager;
mod ship_worth;
pub use fleet_manager::FleetManager;
pub use fleet_manager::FleetManagerReceiver;
pub use messanger::FleetManagerMessanger;
pub use messanger::ShipProcurementMessanger;
pub use ship_procurement_manager::{ShipProcurementManager, ShipProcurementReceiver};
